import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./modules/sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={inter.className}>
        <Sidebar direction="rtl" mode="light">
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
